server:
  port: 8084
  servlet:
    context-path: '/ead-notification-hex/'

spring:
  application:
    name: ead-notification-service-hex
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-notification-hex
    username: postgres
    password: docker
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    addresses: amqps://mhkfajnq:5pZ_MnzN4Ao_pcyv0I_KpTZylHLYn8_i@woodpecker.rmq.cloudamqp.com/mhkfajnq

ead:
  broker:
    exchange:
      notificationCommandExchange: ead.notificationcommand
    queue:
      notificationCommandQueue:
        name: ead.notificationcommand.ms.notification
    key:
      notificationCommandKey: ms.notification

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
